### ISSUE TITLE
Extension version

### ISSUE THREAD

**Issue by remicollet** [binpack/binpack-php#2]
Extension doesn't report its version in phpinfo(), which is a common usage.

More, reflection report version is 0.1.

**Comment by liaohuqiu** [comment]
Hi,  I have added version information for `phpinfo()`. Thank you.

**Comment by remicollet** [comment]
Shoudl be fixed by https://github.com/binpack/binpack-php/pull/4

**Comment by liaohuqiu** [comment]
Thank you.
