### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by remicollet** [binpack/binpack-php#3]
For your information, here is the build test results on Fedora / RHEL / CentOS.
http://copr.fedoraproject.org/coprs/remi/morephp/build/23852/
(you can browse the result, read the build.log, with the build + test suite)

Summary
- always fails on 32bits, ex http://copr-be.cloud.fedoraproject.org/results/remi/morephp/epel-6-i386/php-pecl-binpack-1.0.0-1.remi/build.log
- fails on 64bits, on modern distro (Fedora / RHEL-7), ex http://copr-be.cloud.fedoraproject.org/results/remi/morephp/epel-7-x86_64/php-pecl-binpack-1.0.0-1.remi/build.log

**Comment by remicollet** [comment]
Notice, if you need to test a build before release, I can easily run such a build in a few minutes. Just ask.

**Comment by liaohuqiu** [comment]
@remicollet, thank you for reporting the issues, I will fix them.

**Comment by liaohuqiu** [comment]
@remicollet , I have fixed all of problems on 32bits. I've ran all the tests in my i386 virtual machine.  If convenient, would you run a build? Thank you in advance  :).

**Comment by remicollet** [comment]
Test build : http://copr.fedoraproject.org/coprs/remi/morephp/build/24600/

Build are failing in fedora 21+ / x86_64.
ex: http://copr-be.cloud.fedoraproject.org/results/remi/morephp/fedora-rawhide-x86_64/php-pecl-binpack-1.0.1-0.1.remi/build.log

Some build warning worth to be fixed, especially: the implicit declaration of function 'ntohl' [-Wimplicit-function-declaration]

I will be offline the next days, so won't be able to investigate before Monday

**Comment by remicollet** [comment]
Should be fixed by https://github.com/binpack/binpack-php/pull/4

**Comment by liaohuqiu** [comment]
I have uploaded a release. Thank you for you help, @remicollet ! :)
