### ISSUE TITLE
Homebrew-php

### ISSUE THREAD

**Issue by lucasmichot** [binpack/binpack-php#6]
Hello,

Binpack has been added to homebrew-php: https://github.com/Homebrew/homebrew-php/commit/d43c59f9894e964c821bb8b850117a811cf635f3

Feel free to update Installation instruction fo Mac users:

Happy coding

**Comment by liaohuqiu** [comment]
Hi, I've updated README, https://github.com/binpack/binpack-php/commit/c5b65d816a63a331b915e38f0e2d19a120c325f9#diff-d41d8cd98f00b204e9800998ecf8427e
